1:
	ghdl -a ./fixed_pkg_c.vhd
	ghdl -a ./fixed_float_types_c.vhd
	ghdl -a ./types.vhdl
	ghdl -a ./radix2_e.vhd
	ghdl -a ./radix2_a3.vhd
	ghdl -a ./radix4_e.vhd
	ghdl -a ./radix4_a1.vhd
	ghdl -a ./testbench_e.vhd
	ghdl -a ./testbench_C1.vhd
